CREATE TABLE IF NOT EXISTS PRODUCTS (
  PNO TEXT PRIMARY KEY,
  NAME TEXT NOT NULL,
  PRICE INTEGER,
  YEAR INTEGER
  );
  
INSERT INTO PRODUCTS (PNO, NAME, YEAR, PRICE) VALUES
  ('P1', 'Laptop', 2010, 20000),
  ('P2', 'Tablet', 2015, 20000),
  ('P3', 'Smartphone', 2018, 30000),
  ('P4', 'Smartwatch', 2019, 35000);

SELECT DISTINCT PRICE FROM PRODUCTS;
SELECT COUNT(NAME) FROM PRODUCTS;
SELECT AVG(PRICE) FROM PRODUCTS;
SELECT SUM(PRICE) FROM PRODUCTS;

